import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Color_Emoji } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const notoColorEmoji = Noto_Color_Emoji({
    variable: "--noto-color-emoji",
    subsets: ["emoji"],
    weight: "400",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        {/* <head>
            <title>Title</title>
            <meta name='description' content='Description' />
        </head> */}
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            {children}
        </body>
    </html>
  );
}
